Add support for CAF/Alac audio
RustAudio/audrey pull request #12
Opened 2017-01-29 15:29 UTC by est31

Adds support for the Alac codec, right now only inside the CAF container.

Also, ALAC is the only format in CAF that's supported currently.

Fixes #5.

r? @mitchmindtree

2017-02-07 18:55 UTC, est31 commented
ping @mitchmindtree

2017-02-08 03:29 UTC, mitchmindtree commented
Ahh I forgot about this, thanks for the reminder @est31, will look at this asap :+1:

2017-02-08 11:49 UTC, mitchmindtree requested changes
Just a few minor things, otherwise looks great! Nice one :)

Oh also, it would be great if you got a chance to add it to the chain in the `sine.rs` example, but probs not totally necessary.

2017-02-08 11:49 UTC, mitchmindtree commented on README.md
> +| ALAC (within CAF) | YES | - | caf_alac | [caf](https://crates.io/crates/caf) [alac](https://crates.io/crates/alac) |
Looks like the table is missing the extensions column:

<img width="747" alt="screen shot 2017-02-08 at 10 38 53 pm" src="https://cloud.githubusercontent.com/assets/4587373/22735812/88618f7e-ee4f-11e6-82b1-e18fbab1b66d.png">

2017-02-08 11:49 UTC, mitchmindtree commented on src/lib.rs
> +    #[cfg(feature="caf")]
Should this be the `caf_alac` feature?

2017-02-08 11:49 UTC, mitchmindtree commented on src/lib.rs
> +            #[cfg(feature="caf")]
and this

2017-02-08 11:52 UTC, mitchmindtree commented
Oh also, would you mind adding a line to the `.travis.yml` script section that *just* tests the `caf_alac` feature? I think it's useful to have travis test each feature individually as it is easy to forget to add a missing feature-gate, etc when testing locally.

2017-02-09 06:34 UTC, est31 commented
@mitchmindtree can you look at it again?

2017-02-09 12:20 UTC, mitchmindtree approved these changes
Looks good to me!

2017-02-09 20:29 UTC, merged